spring:
  profiles:
    include:
      - mongodb
      - mysql
      - s3
      - ffmpeg
      - redis
      - elasticsearch
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB